name = "japan-trip-ideas"
type = "javascript"
compatibility_date = "2024-08-13"

# Cloudflare Pages configuration
pages_build_output_dir = "public"

[env.production]
routes = [
  { pattern = "yonatanyadgar.com/japan_ideas", zone_name = "yonatanyadgar.com" }
]
